### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Nielssg** [iiegor/chrome-material#45]
Adding too many tabs will alter the size of the browser negatively :(

![image](https://cloud.githubusercontent.com/assets/20494853/18433224/bd052a62-78e6-11e6-85bc-15cd50530491.png)

**Comment by iiegor** [comment]
Maybe this looks better? ![](http://image.prntscr.com/image/8a611a62fd58441da465d78136a22760.png)

Thanks for reporting! :smile:

**Comment by Nielssg** [comment]
Great :)
